### ISSUE TITLE
Struct 02

### ISSUE THREAD

**Issue by fsantanna** [rn-rodrigues/LP1#3]
https://github.com/rn-rodrigues/LP1/blob/ab45323d2e9c1388531417f09f7415287b790ce0/lab-01/Lab%2023.05/struct2.c#L5

- Usar maiúsculas para os tipos e minúsculas para os campos e variáveis
- `struct casa` só tem um campo? Não faz sentido uma struct com um só campo
- É pra ter uma `preenche_casa` e uma `preenche_vila` (que chama `preenche_casa`)

**Comment by rn-rodrigues** [comment]
Corrigido professor.

**Comment by fsantanna** [comment]
O último item continua em aberto.

**Comment by rn-rodrigues** [comment]
Corrigido professor.
